#development environment
version: '3.7'
services:
  frontend:
    build: 
      context: .
      target: development-stage
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true